from __future__ import annotations

from datetime import datetime

from .models import LoopConfig


def default_session_id() -> str:
    return datetime.now().strftime("session_%Y%m%d_%H%M%S")


def build_config(
    *,
    output_root: str = "runs/vlm_loop",
    fps: int = 2,
    max_steps: int = 12,
    max_iterations: int = 2,
    max_sequences_per_iter: int = 16,
    max_returned_sequences_per_video: int = 4,
    action_length_cap: int = 6,
    timeout_sec: float = 120.0,
    agents_per_iteration: int = 4,
    retry_count: int = 2,
    seed: int = 0,
    task_prompt: str = "",
    llm_backend: str = "vllm",
    ollama_url: str = "http://192.168.0.51:11434",
    ollama_model: str = "qwen3-vl:8b",
    ollama_num_ctx: int = 16384,
    vllm_url: str = "http://192.168.0.51:8000",
    vllm_model: str = "Qwen/Qwen3-VL-8B-Instruct-FP8",
    disable_thinking: bool = True,
    greedy: bool = False,
    top_p: float = 0.8,
    top_k: int = 20,
    temperature: float = 0.7,
    repetition_penalty: float = 1.0,
    presence_penalty: float = 1.5,
    out_seq_length: int = 16384,
    prompt_config_path: str = "src/vlm_loop/prompt_config.json",
    max_prompt_frames: int = 2,
    initial_bootstrap_enabled: bool = True,
    initial_bootstrap_episode_index: int = 0,
    initial_bootstrap_num_actions: int = 6,
    initial_bootstrap_actions: list[str] | None = None,
    render_terminal: bool = False,
    debug: bool = False,
) -> LoopConfig:
    return LoopConfig(
        output_root=output_root,
        fps=fps,
        max_steps=max_steps,
        max_iterations=max_iterations,
        max_sequences_per_iter=max_sequences_per_iter,
        max_returned_sequences_per_video=max_returned_sequences_per_video,
        action_length_cap=action_length_cap,
        timeout_sec=timeout_sec,
        agents_per_iteration=agents_per_iteration,
        retry_count=retry_count,
        seed=seed,
        task_prompt=task_prompt,
        llm_backend=llm_backend,
        ollama_url=ollama_url,
        ollama_model=ollama_model,
        ollama_num_ctx=ollama_num_ctx,
        vllm_url=vllm_url,
        vllm_model=vllm_model,
        disable_thinking=disable_thinking,
        greedy=greedy,
        top_p=top_p,
        top_k=top_k,
        temperature=temperature,
        repetition_penalty=repetition_penalty,
        presence_penalty=presence_penalty,
        out_seq_length=out_seq_length,
        prompt_config_path=prompt_config_path,
        max_prompt_frames=max_prompt_frames,
        initial_bootstrap_enabled=initial_bootstrap_enabled,
        initial_bootstrap_episode_index=initial_bootstrap_episode_index,
        initial_bootstrap_num_actions=initial_bootstrap_num_actions,
        initial_bootstrap_actions=list(initial_bootstrap_actions or []),
        render_terminal=render_terminal,
        debug=debug,
    )
