from __future__ import annotations

from typing import Any


PRIMARY_KEYS = (
    "current_run_wins",
    "current_run_levels_solved",
    "behavioral_success_rate",
    "hgt_behavioral_gain",
    "trajectory_efficiency",
    "M0_count",
    "M1_count",
    "M2_count",
    "M3_count",
    "M4_count",
    "M4_validated",
    "M5_count",
    "M6_count",
    "M7_count",
    "ModelVersion",
    "GPU_memory_GB",
    "active_actor_processes",
    "active_ingest_workers",
    "active_derivation_workers",
    "sampling_rate",
    "ingestion_rate",
    "derivation_rate",
    "sampling_backlog",
    "canonical_apply_latency_ms",
)


def build_primary_dashboard(runtime_metrics: dict[str, Any], diagnostic: dict[str, Any]) -> dict[str, Any]:
    levels = dict(runtime_metrics.get("memory_levels", {}))
    transfer_trials = int(runtime_metrics.get("transfer_trials", 0))
    transfer_scopes = int(runtime_metrics.get("transfer_trust_scopes", 0))
    false_transfers = int(runtime_metrics.get("failed_transfer_scopes", 0))
    deliberation_decisions = int(diagnostic.get("deliberation_decisions", 0))
    reasoning_cycles = int(diagnostic.get("reasoning_cycles", 0))
    initial_sum = float(diagnostic.get("initial_candidate_score", 0.0))
    best_sum = float(diagnostic.get("best_candidate_score", 0.0))
    hgt_samples = int(diagnostic.get("hgt_inference_samples", 0))
    training_reports = int(diagnostic.get("hgt_training_reports", 0))
    dashboard = {
        "current_run_wins": float(diagnostic.get("current_run_wins", runtime_metrics.get("current_run_wins", 0.0))),
        "current_run_levels_solved": int(diagnostic.get("current_run_levels_completed", runtime_metrics.get("current_run_levels_completed", 0))),
        "behavioral_success_rate": float(diagnostic.get("behavioral_success_rate", 0.0)),
        "behavioral_success_gain": float(diagnostic.get("behavioral_success_gain", 0.0)),
        "hgt_on_behavioral_success": float(diagnostic["hgt_on_behavioral_success"]) if "hgt_on_behavioral_success" in diagnostic else None,
        "hgt_off_behavioral_success": float(diagnostic["hgt_off_behavioral_success"]) if "hgt_off_behavioral_success" in diagnostic else None,
        "hgt_behavioral_gain": float(diagnostic["hgt_behavioral_gain"]) if "hgt_behavioral_gain" in diagnostic else None,
        "hgt_selected_branch": str(diagnostic["hgt_evaluation_branch"]) if diagnostic.get("hgt_evaluation_branch") in {"hgt_on", "hgt_off"} else None,
        "trajectory_efficiency": float(runtime_metrics.get("trajectory_efficiency", 0.0)),
        "M0_count": int(levels.get("M0", 0)),
        "M1_count": int(levels.get("M1", 0)),
        "M2_count": int(levels.get("M2", 0)),
        "M3_count": int(levels.get("M3", 0)),
        "M4_count": int(levels.get("M4", 0)),
        "M4_validated": int(runtime_metrics.get("m4_validated", 0)),
        "M5_count": int(levels.get("M5", 0)),
        "M6_count": int(levels.get("M6", 0)),
        "M7_count": int(levels.get("M7", 0)),
        "m6_equivalence_confidence": float(runtime_metrics.get("m6_equivalence_confidence", 0.0)),
        "m6_preference_relations": int(runtime_metrics.get("m6_preference_relations", 0)),
        "m7_multi_strategy_outcomes": int(runtime_metrics.get("m7_multi_strategy_outcomes", 0)),
        "m7_replan_attempts": int(runtime_metrics.get("m7_replan_attempts", 0)),
        "m7_replan_successes": int(runtime_metrics.get("m7_replan_successes", 0)),
        "m7_replanning_recovery_rate": float(runtime_metrics.get("m7_replanning_recovery_rate", 0.0)),
        "memory_growth_rate": float(runtime_metrics.get("persistent_memory_growth_ratio", 0.0)),
        "compression_ratio": float(runtime_metrics.get("compression_ratio", 0.0)),
        "prediction_error": float(runtime_metrics.get("prediction_error", 0.0)),
        "symbol_occurrences": int(runtime_metrics.get("symbol_occurrences", 0)),
        "symbol_windows": int(runtime_metrics.get("symbol_windows", 0)),
        "symbolic_M0_count": int(runtime_metrics.get("symbolic_M0_count", 0)),
        "symbolic_M1N_count": int(runtime_metrics.get("symbolic_M1N_count", 0)),
        "cross_modal_correspondences": int(runtime_metrics.get("cross_modal_correspondences", 0)),
        "symbol_transfer_trials": int(runtime_metrics.get("symbol_transfer_trials", 0)),
        "symbol_composition_successes": int(runtime_metrics.get("symbol_composition_successes", 0)),
        "hgt_symbol_nodes": int(diagnostic.get("hgt_symbol_nodes", 0)),
        "hgt_symbol_edges": int(diagnostic.get("hgt_symbol_edges", 0)),
        "hgt_grounding_loss": float(diagnostic.get("hgt_grounding_loss", 0.0)),
        "hgt_grounding_calibration": float(diagnostic.get("hgt_grounding_calibration", 0.0)),
        "grounding_G0_count": int(runtime_metrics.get("grounding_G0_count", 0)),
        "grounding_G1_count": int(runtime_metrics.get("grounding_G1_count", 0)),
        "grounding_G2_count": int(runtime_metrics.get("grounding_G2_count", 0)),
        "grounding_G3_count": int(runtime_metrics.get("grounding_G3_count", 0)),
        "grounding_G4_count": int(runtime_metrics.get("grounding_G4_count", 0)),
        "grounding_G5_count": int(runtime_metrics.get("grounding_G5_count", 0)),
        "grounding_active_count": int(runtime_metrics.get("grounding_active_count", 0)),
        "grounding_suspended_count": int(runtime_metrics.get("grounding_suspended_count", 0)),
        "grounding_mean_confidence": float(runtime_metrics.get("grounding_mean_confidence", 0.0)),
        "grounded_action_influence": int(runtime_metrics.get("grounded_action_influence", 0)),
        "symbol_prediction_gain": float(runtime_metrics.get("symbol_prediction_gain", 0.0)),
        "H16_C0_score": diagnostic.get("h16_C0_score"),
        "H16_C1_score": diagnostic.get("h16_C1_score"),
        "H16_C2_score": diagnostic.get("h16_C2_score"),
        "H16_C3_score": diagnostic.get("h16_C3_score"),
        "H16_aligned_advantage": diagnostic.get("h16_aligned_advantage"),
        "H16_heldout_causal_effect": diagnostic.get("h16_heldout_causal_effect"),
        "cross_family_transfer": float(runtime_metrics.get("cross_family_transfer", 0.0)),
        "false_transfer_rate": (false_transfers / transfer_scopes) if transfer_scopes else None,
        "reasoning_cycles": (reasoning_cycles / deliberation_decisions) if deliberation_decisions else None,
        "final_vs_initial_candidate_improvement": ((best_sum - initial_sum) / deliberation_decisions) if deliberation_decisions else None,
        "deliberation_behavior_improvement": float(diagnostic.get("changed_decisions_with_better_outcome_rate", 0.0)) if deliberation_decisions else None,
        "HGT_consequence_error": float(diagnostic.get("hgt_consequence_error", 0.0)) if hgt_samples else None,
        "HGT_strategy_ranking_accuracy": float(diagnostic.get("hgt_strategy_ranking_accuracy", 0.0)) if hgt_samples else None,
        "HGT_candidate_refinement_success": float(diagnostic.get("hgt_candidate_refinement_success", 0.0)) if hgt_samples else None,
        "HGT_training_loss": float(diagnostic.get("hgt_training_loss", 0.0)) if training_reports else None,
        "HGT_validation_loss": float(diagnostic.get("hgt_validation_loss", 0.0)) if training_reports else None,
        "historical_retention": float(diagnostic.get("historical_retention", 0.0)) if training_reports else None,
        "current_curriculum_gain": float(diagnostic.get("current_curriculum_gain", 0.0)) if training_reports else None,
        "cross_family_validation_gain": float(diagnostic.get("cross_family_validation_gain", 0.0)) if training_reports else None,
        "ModelVersion": str(diagnostic.get("model_version", "untrained")),
        "GPU_memory_GB": round(float(diagnostic.get("gpu_memory_current_bytes", diagnostic.get("gpu_memory_bytes", 0))) / (1024.0 ** 3), 2),
        "inference_latency": float(diagnostic.get("inference_latency_ms", 0.0)),
        "training_step_latency": float(diagnostic.get("training_step_latency_ms", 0.0)),
        "active_actor_processes": int(diagnostic.get("active_actor_processes", 0)),
        "active_ingest_workers": int(diagnostic.get("active_ingest_workers", 0)),
        "active_derivation_workers": int(diagnostic.get("active_derivation_workers", 0)),
        "sampled_steps": int(diagnostic.get("sampled_steps", 0)),
        "ingested_steps": int(diagnostic.get("ingested_steps", 0)),
        "sampling_backlog": int(diagnostic.get("sampling_backlog", 0)),
        "ingest_queue_depth": int(diagnostic.get("ingest_queue_depth", 0)),
        "derivation_queue_depth": int(diagnostic.get("derivation_queue_depth", 0)),
        "sampling_rate": float(diagnostic.get("sampling_rate", 0.0)),
        "ingestion_rate": float(diagnostic.get("ingestion_rate", 0.0)),
        "derivation_rate": float(diagnostic.get("derivation_rate", 0.0)),
        "memory_result_queue_depth": int(diagnostic.get("memory_result_queue_depth", 0)),
        "canonical_apply_rate": float(diagnostic.get("canonical_apply_rate", 0.0)),
        "canonical_apply_latency_ms": float(diagnostic.get("canonical_apply_latency_ms", 0.0)),
        "canonical_batch_size": int(diagnostic.get("canonical_batch_size", 0)),
        "coordinator_action_requests": int(diagnostic.get("coordinator_action_requests", 0)),
        "policy_snapshot_generation": int(diagnostic.get("policy_snapshot_generation", 0)),
        "policy_snapshot_refreshes": int(diagnostic.get("policy_snapshot_refreshes", 0)),
    }
    return {key: dashboard[key] for key in PRIMARY_KEYS}
