"""ARC-AGI3 v6 cognitive interaction learner."""

from v6.main import V6Config, V6System
from v6.hypothesis_suite_performance import install_hypothesis_suite_performance_policy
from v6.hypothesis_suite_performance_compat import apply_hypothesis_suite_performance_compatibility
from v6.h08_world_model_prediction_repair import install_h08_world_model_prediction_repair
from v6.v042_policy import install_v042_policy
from v6.v042_compat import apply_v042_compatibility
from v6.suite_runtime_repairs import install_suite_runtime_repairs
from v6.suite_runtime_repairs_compat import install_suite_runtime_repairs_compat
from v6.suite_runtime_profiler import install_suite_runtime_profiler
from v6.concept_validation_fastpath import install_concept_validation_fastpath
from v6.concept_validation_fastpath_compat import install_concept_validation_fastpath_compat
from v6.concept_validation_fastpath_fixups import install_concept_validation_fastpath_fixups
from v6.concept_validation_sparse_cache import install_concept_validation_sparse_cache
from v6.concept_validation_profiler_context_fix import install_concept_validation_profiler_context_fix
from v6.concept_validation_profiler_wiring import install_concept_validation_profiler_wiring
from v6.concept_validation_relevance_pruning import install_concept_validation_relevance_pruning
from v6.concept_validation_relevance_compat import install_concept_validation_relevance_compat
from v6.concept_validation_history import install_concept_validation_history
from v6.higher_order_evidence_history import install_higher_order_evidence_history
from v6.world_model_validation_history import install_world_model_validation_history
from v6.cumulative_evidence_reporting import install_cumulative_evidence_reporting
from v6.h05_temporal_order_compat import install_h05_temporal_order_compat

install_hypothesis_suite_performance_policy()
apply_hypothesis_suite_performance_compatibility()
install_h08_world_model_prediction_repair()
install_v042_policy()
apply_v042_compatibility()
install_suite_runtime_repairs()
install_suite_runtime_repairs_compat()
install_suite_runtime_profiler()
install_concept_validation_fastpath()
install_concept_validation_fastpath_compat()
install_concept_validation_fastpath_fixups()
install_concept_validation_sparse_cache()
install_concept_validation_profiler_context_fix()
install_concept_validation_profiler_wiring()
install_concept_validation_relevance_pruning()
install_concept_validation_relevance_compat()
install_concept_validation_history()
install_higher_order_evidence_history()
install_world_model_validation_history()
install_cumulative_evidence_reporting()
install_h05_temporal_order_compat()

__all__ = ["V6Config", "V6System"]
